sudo: false
language: python
python:
- "3.6"
- "3.7-dev"
before_install:
- sudo apt-get install graphviz
install: pip install tox-travis
script: xvfb-run tox
deploy:
  provider: pypi
  user: tom-mi
  password:
    secure: "gSG1yH7QHfpViLWwliC8zuusz2BTUvIMuOEhpGoDu5KyVPbcEyRsAcnZNdHBSub1ryQk3H2uA/VQyPNBTvcSv963LSv788nFqK8vb/ulyuNIl5xAt+vdyZ6oRJFQEDK56OREzALln2GtuEakUyMIKjJv2BfLobFIQTNpgQ+gsLReG3TOY77RDa7ZEfHEacnFD0p/OhiQAY2azhLRnibumfBHjXW3u0xFvZa5sqsGFzyV6oPUXFulEKYOyfvZspuVm/kf0n0blSL4/CSogQtBk0RDkvdGAnl+ylaSSTNI7DIySjwmqhQaNbYlsvOOXvMdXRFYCjf8bdbPQRGTI0EhgCYyP2lalq9zalPQdYcBGawKPd09vtY2FsTiLiRc7HAdCHeX/mNMdj7/gbnYhIgep0yNAuyBYEqdaL4AUt0XK4Ah7AvMNDBaFNNynAvAVN6sSd65Db6ctobrnVpr2DUo9x9yELnFA6CFsnRIIzcuFVysTvrZ9NQFUdio4tk9YSvZPjLsNOnhPyqnYFbq3/bpxoyHKXt0U7F3ZZV1CBxTxgguddqzcQtSS/vqx10Zg5s3xF6cHr4QxdsOB70N04tQ03cjnXB+7N5+5U1URfaK/+yp+Dio0r8djNXC98NOhw1dA9WftFXlIz+kycRzVK2aJYh/FuNTq5jlGdy1qvPobsY="


  on:
    tags: true
    python: 3.7-dev
    repo: tom-mi/python-async2v
  distributions: bdist_wheel
