sudo: false
language: python
python:
- "3.6"
- "3.7-dev"
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: tom-mi
  password:
    secure: "JwaVcp+ph2HrkLvOwGZrHTWoI4lIGXTp5hp6eJRX1ri7WMC5HUkVZyypSbzZbs2wqazE78HKO7APtcFp6sSqYcyZhYorQSk4L1pnc1DlnnGvXCHO8gRagVOuojoj3apRPLoiYkZBmcxEQmk7ApG8o6cezT2d0YM+6YnTzMHe/nm+xqBk0zZY1RuoDOQYOmjKjXyjui608WYiuIcyOqzQIXHT7r+2HlAuyIduXvyi77qvmVw1hl/X4EqvkN3jqjKIIgbP22VJ9msrEaFvEB0gEcy5Hlb8TR+uKf8hD8u6KXlJJAiJhr1RYTlo6X3XK3YzCokBApUgyntTZHt72/K2fNuepwyAzFrtoPWYhjW2QQ/U1pG/ue4BMO+s10f06zjB+8xNHsufFwCGIaJPsAqKoed4PyB2pSL6GOLErzyFQ1nGpjUJ3jDBG7F2sEg117Hwziaasjhl6ee7HcUqRnjXNNitud7kZdZBqmBo+PTdSea01aog0AJJg5wKGWJbJjq8D/+2VFBpTvpXZjeT7i5KF19Z8dWDlsFwe244Q0Kf7nSd5A2YGBEIokpc24vUl5FyQTLr/48go8+HCq7cTO5iCM7Qm1N9P/5IMqbRCKZQ1Un02qwjXDHq3/qoImsX5ZmEBW08LQ5cneRKFDrMGQic0Rrx/0N33XoLr0+uh4HJuEY="

  on:
    tags: true
    python: 3.7-dev
    repo: tom-mi/python-async2v
  distributions: bdist_wheel
